//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CompteRendu
{
	private string titre
	{
		get;
		set;
	}

	private string contenu
	{
		get;
		set;
	}

	private static int nbCaractMax
	{
		get;
		set;
	}

	public virtual Jour Date
	{
		get;
		set;
	}

	public virtual void setCR(object String newCR)
	{
		throw new System.NotImplementedException();
	}

	public virtual string getCR()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getTitre()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setTitre(object String newTitre)
	{
		throw new System.NotImplementedException();
	}

}

