//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Jour
{
	private int numero
	{
		get;
		set;
	}

	/// <summary>
	/// passé/prst/futur
	/// </summary>
	private string statut
	{
		get;
		set;
	}

	public virtual IEnumerable<Activite> Activites
	{
		get;
		set;
	}

	public virtual CompteRendu CompteRendu
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual Mission Mission
	{
		get;
		set;
	}

	public virtual bool sortieExte()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ajouterActivite(object Activite act)
	{
		throw new System.NotImplementedException();
	}

	public virtual void supprActivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifAcitivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setStatut()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getStatut()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ajouterCR()
	{
		throw new System.NotImplementedException();
	}

}

