//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Lieu
{
	private string nom
	{
		get;
		set;
	}

	/// <summary>
	/// LieuBase est à [0,0] en coordonnées, pas en px;
	/// les autres lieu sont donc localisés par rapport à la base, grace à leurs coordonnées
	/// 
	/// </summary>
	private double[,] position
	{
		get;
		set;
	}

	/// <summary>
	/// chemin de l'image carte. Récupéré à partir du fichier XML chagré
	/// </summary>
	private static string carte
	{
		get;
		set;
	}

	/// <summary>
	/// echelle de la carte, en metre/pixel
	/// </summary>
	private static int echelleMpx
	{
		get;
		set;
	}

	public virtual void setPosition(object double x, object double y)
	{
		throw new System.NotImplementedException();
	}

	public virtual double[,] getPosition()
	{
		throw new System.NotImplementedException();
	}

	public virtual string getNom()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setNom(object String newNom)
	{
		throw new System.NotImplementedException();
	}

	public virtual void setNom(object String newNom)
	{
		throw new System.NotImplementedException();
	}

}

